/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BenchRouteImport } from './routes/bench'
import { Route as OsceRouteImport } from './routes/osce'
import { Route as RpdRouteImport } from './routes/rpd'
import { Route as SinusRouteImport } from './routes/sinus'
import { Route as LockedSlugRouteImport } from './routes/locked.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchRoute = BenchRouteImport.update({
  id: '/bench',
  path: '/bench',
  getParentRoute: () => rootRouteImport,
} as any)
const OsceRoute = OsceRouteImport.update({
  id: '/osce',
  path: '/osce',
  getParentRoute: () => rootRouteImport,
} as any)
const RpdRoute = RpdRouteImport.update({
  id: '/rpd',
  path: '/rpd',
  getParentRoute: () => rootRouteImport,
} as any)
const SinusRoute = SinusRouteImport.update({
  id: '/sinus',
  path: '/sinus',
  getParentRoute: () => rootRouteImport,
} as any)
const LockedSlugRoute = LockedSlugRouteImport.update({
  id: '/locked/$slug',
  path: '/locked/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bench': typeof BenchRoute
  '/osce': typeof OsceRoute
  '/rpd': typeof RpdRoute
  '/sinus': typeof SinusRoute
  '/locked/$slug': typeof LockedSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bench': typeof BenchRoute
  '/osce': typeof OsceRoute
  '/rpd': typeof RpdRoute
  '/sinus': typeof SinusRoute
  '/locked/$slug': typeof LockedSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bench': typeof BenchRoute
  '/osce': typeof OsceRoute
  '/rpd': typeof RpdRoute
  '/sinus': typeof SinusRoute
  '/locked/$slug': typeof LockedSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bench' | '/osce' | '/rpd' | '/sinus' | '/locked/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bench' | '/osce' | '/rpd' | '/sinus' | '/locked/$slug'
  id:
    '__root__' | '/' | '/bench' | '/osce' | '/rpd' | '/sinus' | '/locked/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchRoute: typeof BenchRoute
  OsceRoute: typeof OsceRoute
  RpdRoute: typeof RpdRoute
  SinusRoute: typeof SinusRoute
  LockedSlugRoute: typeof LockedSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench': {
      id: '/bench'
      path: '/bench'
      fullPath: '/bench'
      preLoaderRoute: typeof BenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/osce': {
      id: '/osce'
      path: '/osce'
      fullPath: '/osce'
      preLoaderRoute: typeof OsceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpd': {
      id: '/rpd'
      path: '/rpd'
      fullPath: '/rpd'
      preLoaderRoute: typeof RpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sinus': {
      id: '/sinus'
      path: '/sinus'
      fullPath: '/sinus'
      preLoaderRoute: typeof SinusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locked/$slug': {
      id: '/locked/$slug'
      path: '/locked/$slug'
      fullPath: '/locked/$slug'
      preLoaderRoute: typeof LockedSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchRoute: BenchRoute,
  OsceRoute: OsceRoute,
  RpdRoute: RpdRoute,
  SinusRoute: SinusRoute,
  LockedSlugRoute: LockedSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
